apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-prj-deployment
  labels:
    app: java-prj
spec:
  replicas: 2
  selector:
    matchLabels:
      app: java-prj
  template:
    metadata:
      labels:
        app: java-prj
    spec:
      containers:
      - name: java
        image: maroofatanweer/java-prj:latest
        ports:
        - containerPort: 8080
