apiVersion: v1
kind: Namespace
metadata:
  name: java-prj-ns

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-prj-deployment
  namespace: java-prj-ns
  labels:
    app: java-prj
spec:
  replicas: 2
  selector:
    matchLabels:
      app: java-prj
  template:
    metadata:
      labels:
        app: java-prj
    spec:
      containers:
      - name: java
        image: maroofatanweer/java-prj:latest
        ports:
        - containerPort: 8080
        
---
apiVersion: v1
kind: Service
metadata:
  namespace: java-prj-ns
  labels:
    app: java-prj
  name: java-prj-svc
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 31100
  selector:
    app: java-prj
